" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2019 Jan 26
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

set backup		" keep a backup file (restore to previous version)
if has('persistent_undo')
  set undofile	" keep an undo file (undo changes after closing)
endif

" Switch on highlighting the last used search pattern.
set hlsearch

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END


" Configurations for vim.wasm
set nocompatible
set encoding=utf-8

" Note: Configs for vim.wasm should be written in /root/.vim/vimrc
